### ISSUE TITLE
failed to map segment from shared object

### ISSUE THREAD

**Issue by hppyworld** [klo2k/nexus3-docker#14]
There is a bug on raspberry pi arm64 ubuntu
java.lang.UnsatisfiedLinkError: /nexus-data/tmp/jna1594202494393200442.tmp: /nexus-data/tmp/jna1594202494393200442.tmp: failed to map segment from shared object

Please tell me how to fix it. thanks

**Comment by klo2k** [comment]
I'm gonna need to dig my Ubuntu image out to check this out.

In the mean time, how did you get to this error?

**Comment by hppyworld** [comment]
I just simply run your image with docker compose and volumes are externally mounter to specific local path. On Raspberry Pi running Ubuntu arm 64

**Comment by hppyworld** [comment]
I found the issue took long time to understand it. Problem was fstab connected harddisk had no exec permission. user in fstab was overridding exec. So this strange issues happened in nexus. 
thanks. Its solved now.

**Comment by klo2k** [comment]
I'm glad you got to the bottom of this.  Hopefully your solution will help others with the same problem.

Another thing to check would be ownership - especially when bind-mounting from host filesystem (I do that btw :slightly_smiling_face: ).

Make sure your host's directory is [owned by 200:200](https://github.com/klo2k/nexus3-docker/blob/1b29e600c566e09fb7318e59ce9542743387c358/Dockerfile#L87-L88) - the uid:gid nexus is running inside the container.

Alternatively, use actual [docker-volume](https://docs.docker.com/storage/volumes/) to avoid this hassle.
