### ISSUE TITLE
Official dockerfile arm64 build is working now

### ISSUE THREAD

**Issue by timmychiu** [klo2k/nexus3-docker#18]
FYI

https://github.com/sonatype/docker-nexus3/blob/master/Dockerfile

arm64 machine (k3s-arm64) to build and run

After build and run, no error log found in normal use (I only used maven repo, docker repo).

**Comment by klo2k** [comment]
Oh nice, thanks for the heads-up!

Gonna give this a try and see what happens.

I wonder why they still don't publish the arm64 version on Docker hub 🤔
