### ISSUE TITLE
How frequently do you release?

### ISSUE THREAD

**Issue by zlatkoc** [klo2k/nexus3-docker#23]
Current version of Sonatype Nexus Repository is 3.61.0.

How frequently do you release arm64 images? Latest version build with your tool submitted to docker hub is 3.43.0.

**Comment by klo2k** [comment]
Sorry for the lack of release, I'm working on auto-build and release from upstream which should help keep this within 1 day of upstream release.

Until that's done, I'll manually update to the latest version soon - will close this when I release.

**Comment by klo2k** [comment]
I've pushed the latest version - [3.61.0-02](https://hub.docker.com/r/klo2k/nexus3/tags).

Once automated tests are done I can start auto-releasing when upstream changes version.
