### ISSUE TITLE
Bump nexus3 version ton 3.66

### ISSUE THREAD

**Issue by globlit** [klo2k/nexus3-docker#25]
Hi :) 

First of all, thanks for this image, which saves me a tons of time !
Is it possible to re-run the pipeline to get the latest version of nexus3 ? 

I checked the github actions and realised you had a way to extract the latest main version number. I suppose a "simple" rerun of the action pipeline can upgrade the image ?

**Comment by klo2k** [comment]
Sure, I'll do this over the weekend.

I was preparing for auto-update to my "release" version - but need to put together some tests first...

**Comment by saw303** [comment]
Would be super if this could be done with the current latest version 3.67.1. Thank you so much

**Comment by klo2k** [comment]
Sorry for the wait, just pushed `klo2k/nexus3:3.67.1-01`.

GH workflow now push latest Nexus as `klo2k/nexus3:development` tag twice a week (if there's no bug with my github workflow 😅).

Please test before using that build though - there's no test associated with that yet - and I do use that tag for my own testing too...

**Comment by saw303** [comment]
excellent. thank you very much
